print("Coke Fruit Shop")
print("***************************************")
print("Coconut x",       8,25,"THB - ", 8*25,"THB")
print("Grape x",        12,78,"THB - ",12*78,"THB")
print("Mango x",         6,20,"THB - ", 6*20,"THB")
print("Papaya Pok Pok x",4,21,"THB - ", 4*21,"THB")
print("Apple x",         19,8,"THB - ", 19*8,"THB")
print("***************************************")
print("Total",(8*25)+(12*78)+(6+20)+(4*21)+(19*8),"THB")
print("Thank You Coke Fruit Shop")
print("***************************************")